version = 0.1

[default.deploy.parameters]
stack_name = "demo-vinculacion"
resolve_s3 = true
s3_prefix = "demo-vinculacion"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
